Repository seanmbills/FamilyFriendlyBreweryTracker, pull requests merged in 2019-11, with the labels that each got.

#83 Pete.more screen
  App.js
  package-lock.json
  package.json
  src/api/InputValidation.js
  src/components/BreweryForm.js
  src/context/BreweryContext.js
  src/screens/BreweryListScreen.js
  src/screens/CreateBreweryScreen.js
  src/screens/EditBreweryScreen.js
  src/screens/MoreScreen.js
  src/screens/WelcomeScreen.js
Labels: enhancement

#85 Fixed default state object distance in SearchBar component so now the…
  src/components/SearchBar.js
Labels: bug

#88 Pete.navigation tabs
  App.js
  assets/buffering.gif
  package-lock.json
  package.json
  src/components/BreweryForm.js
  src/components/BufferPopup.js
  src/components/NavigationButton.js
  src/components/PasswordField.js
  src/components/WelcomeButton.js
  src/context/AuthContext.js
  src/context/BreweryContext.js
  src/screens/BreweryListScreen.js
  src/screens/CreateBreweryScreen.js
  src/screens/EditBreweryScreen.js
  src/screens/ForgotPasswordScreen.js
  src/screens/LoginScreen.js
  src/screens/MoreScreen.js
  src/screens/PasswordResetSuccessScreen.js
  src/screens/RegistrationScreen.js
  src/screens/UpdateAccountScreen.js
  src/screens/WelcomeScreen.js
Labels: documentation, enhancement

#90 Sean.add profile upload
  assets/EmptyProfilePic.png
  assets/PhotosComingSoon.jpg
  assets/UploadPhotoIcon.jpg
  package-lock.json
  package.json
  src/components/BreweryForm.js
  src/components/ResultDetails.js
  src/context/AuthContext.js
  src/context/BreweryContext.js
  src/screens/BreweryDetailsScreen.js
  src/screens/BreweryListScreen.js
  src/screens/MoreScreen.js
  src/screens/RegistrationScreen.js
  src/screens/UpdateAccountScreen.js
Labels: enhancement

#102 fixed signedUrl instances to be properly case sensitive
  package-lock.json
  src/context/AuthContext.js
Labels: bug

#107 Sean.fix set time spinners
  src/components/BreweryForm.js
Labels: bug, enhancement

#106 Sean.fix ratings reviews
  src/context/ReviewContext.js
  src/screens/BreweryDetailsScreen.js
  src/screens/ReadReviewsScreen.js
Labels: bug, enhancement

#112 Pete.guest user
  src/components/SignInPrompt.js
  src/context/AuthContext.js
  src/context/BreweryContext.js
  src/context/ReviewContext.js
  src/screens/MoreScreen.js
  src/screens/UpdateAccountScreen.js
  src/screens/WelcomeScreen.js
  src/screens/WriteReviewScreen.js
Labels: enhancement

#109 Sean.add brewery photos
  src/components/BreweryForm.js
  src/context/BreweryContext.js
Labels: enhancement

#110 added spinner to create/update pages
  src/components/BreweryForm.js
Labels: enhancement

#119 Sean.implement refresh tokens
  package-lock.json
  package.json
  src/components/BreweryForm.js
  src/context/AuthContext.js
  src/context/BreweryContext.js
  src/context/ReviewContext.js
  src/screens/BreweryDetailsScreen.js
  src/screens/MoreScreen.js
  src/screens/UpdateAccountScreen.js
  src/screens/WelcomeScreen.js
  src/screens/WriteReviewScreen.js
Labels: enhancement

#125 fixed issue where results list is set to null when an error occurs in…
  src/components/ResultsList.js
  src/context/BreweryContext.js
Labels: bug

#127 Pete.search zip fixes
  src/components/ResultsList.js
  src/components/SearchBar.js
  src/context/AuthContext.js
  src/screens/BreweryListScreen.js
Labels: enhancement

#129 Sean.fix buffer popup
  package-lock.json
  package.json
  src/context/AuthContext.js
  src/screens/LoginScreen.js
  src/screens/RegistrationScreen.js
  src/screens/WelcomeScreen.js
Labels: bug

#130 cleaned up the list and details UI components
  src/components/ResultDetails.js
  src/components/ResultsList.js
  src/screens/BreweryListScreen.js
Labels: enhancement

#128 Pete.optional brew email web
  src/components/BreweryForm.js
  src/screens/MoreScreen.js
Labels: enhancement

#138 addressed registration screen popup not disappearing correctly
  src/components/BreweryForm.js
  src/screens/RegistrationScreen.js
  src/screens/WelcomeScreen.js
Labels: bug

#139 fixed empty results list display
  src/components/BreweryForm.js
  src/screens/BreweryListScreen.js
Labels: bug

#140 had an unnecessary "onDismiss" function in the dialog popup for the g…
  src/context/AuthContext.js
  src/screens/WelcomeScreen.js
Labels: bug

#142 Read me
  README.md
Labels: documentation

#144 Restricted zip code and phone number input fields on registration scr…
  src/screens/RegistrationScreen.js
Labels: bug

#152 Added call to context method getBrewery() after successfully writing …
  src/screens/WriteReviewScreen.js
Labels: bug

#147 updated search bar file to ask for permissions to use location services;
  package-lock.json
  package.json
  src/components/SearchBar.js
Labels: enhancement

#148 added ability to display in-line ad banners in the brewery list searc…
  package-lock.json
  package.json
  src/components/ResultsList.js
Labels: enhancement

#155 Fixed Search Bar so now if a user alters the zip code, his/her accoun…
  src/components/SearchBar.js
Labels: bug

#159 Pete.guest login ui
  src/components/SignInPrompt.js
  src/screens/UpdateAccountScreen.js
  src/screens/WelcomeScreen.js
Labels: enhancement

#165 Pete.update account nav fixes
  src/screens/UpdateAccountScreen.js
Labels: bug

#166 Reconfigured UI to more closely resemble that for login and registrat…
  .DS_Store
  src/.DS_Store
  src/components/BreweryForm.js
Labels: enhancement
